### ISSUE TITLE
Clearer explanation of rubrics for exercise 7

### ISSUE THREAD

**Issue by ananth1996** [avehtari/BDA_course_Aalto#2]
The rubrics of exercise 7 problem 2 has very vague definitions of what the _model plot_ for the pooled, separate and hierarchical model should be.
It just mentions 

> The following model solution plot is used as a reference in the grading for the separate model:

The actual plots need not be included in the rubrics, but maybe a description of what plots are expected would help when we form a report. Something like 
> The following histograms of a) posterior distribution of mean for 6th machine b) posterior predictive distribution for the 6th machine and c) Posterior distribution of mean for a 7th machine will be used as a reference for the pooled model.

This would then give the student information on what all graphs may be included in the report so that the evaluator will be able to grade better .

Similar things for 
>discussion about question i)

This could also be written as 
> discussion about question i) the posterior distribution of mean of measurement of the 6th machine

**Comment by tsivula** [comment]
Thanks for the feedback. We'll consider doing some changes to the wordings, maybe to the problem description. The revealed rubricks follow the form of the actual rubrick. We just hide some info there. The problem pdf should always contain all the required info.

In this rubrick case, we need to ensure that we do not reveal which histograms apply for which model. That is, we do not want to reveal which plots can be plotted for which model.

**Comment by MansMeg** [comment]
This has now been fixed and can be found in PR #48 .
