### ISSUE TITLE
Add a note about how to use `markmyassignment`

### ISSUE THREAD

**Issue by kunalghosh** [avehtari/BDA_course_Aalto#20]
During the exercise sessions the students were confused (at least I had to explain to 4 students) about how to use `markmyassignment` to validate their solutions.

A note like the following, in exercise PDFs, should be helpful.

> Calling `mark_my_assignment()` without any arguments checks the functions that you are supposed to implement in this assignment.

**Comment by MansMeg** [comment]
Fixed in the last PR.
