### ISSUE TITLE
Clearly state the functions' arguments' names

### ISSUE THREAD

**Issue by AlejandroCatalina** [avehtari/BDA_course_Aalto#21]
There are cases where our test suite for `markmyassignment` checks the functions with some parameter names that must be present in the definition of the student, as in

```r
p_identical_twin <- function(fraternal_prob=..., identical_prob=...) {}
```

If the student then names the function arguments using a different name R will raise an error, so we should just state cleary in the assignment pdf that they must use those same names.

**Comment by MansMeg** [comment]
Now fixed and in PR #47 .
