### ISSUE TITLE
Feature Suggestion: Automatic English Subtitles

### ISSUE THREAD

**Issue by lironmo** [avehtari/BDA_course_Aalto#235]
I'm writing to express my appreciation for the informative and well-produced videos on Panopto's 

I'd like to propose a new feature suggestion: the ability to automatically generate subtitles in English for  your Panopto videos. This would significantly enhance accessibility and improve the overall user experience for viewers.

**Comment by avehtari** [comment]
Thanks for the suggestion. I'll investigate the quality of the automatic captions. A few years ago, Youtube automatic captions were quite bad (probably partially due to my accent), but maybe the systems are now better

**Comment by lironmo** [comment]
Thanks you for your response. We actually finished watching the series of lectures, i will close this suggestion.

If you have any idea for workshop to better understand these topic i would love to hear.
