### ISSUE TITLE
Clearly explain what fraternal and identical twins mean

### ISSUE THREAD

**Issue by AlejandroCatalina** [avehtari/BDA_course_Aalto#25]
It seems that the students have some trouble identifying what these mean. Instead of the current explanation we could add "fraternal twin (two different embryos and then could be of different sex) and identical twin (same egg divides into two, so they share the same sex)", or something of the like.

ping @MansMeg @kunalghosh @adhaka

**Comment by MansMeg** [comment]
Now fixed and in PR #47 .
