### ISSUE TITLE
Simplify exercise 1.3 requirements

### ISSUE THREAD

**Issue by AlejandroCatalina** [avehtari/BDA_course_Aalto#26]
We can also simplify a bit the text of the exercise 1.3. It currently stands as

> The researchers are happy with these preliminary results (about 97% success rate), and wish to get the test to market as soon as possible. How would you advise them? Base your answer on elementary probability calculus.

We could leave it

> The researchers are happy with these preliminary results, and wish to get the test to market as soon as possible. How would you advise them? Base your answer on **bayes' rule computations**.

Some fo the students where puzzled by the "basic calculus" bit.

ping @MansMeg @kunalghosh

**Comment by MansMeg** [comment]
Now fixed and in PR #47 .
