### ISSUE TITLE
Discription of Assignment 1.1 unclear

### ISSUE THREAD

**Issue by filiptypjeu** [avehtari/BDA_course_Aalto#27]
Are you supposed to explain the terms with one sentence, or with one sentence each?

**Comment by AlejandroCatalina** [comment]
One sentence each. This kind of short questions are more easily answered on slack, so everybody sees it immediately.

**Comment by MansMeg** [comment]
Maybe we want to keep it as an issue to clarify in the assignment as well?

**Comment by MansMeg** [comment]
Now fixed and in PR #47 .
