### ISSUE TITLE
`prsf.py` not compatible with Python3 and no documentation of tau output

### ISSUE THREAD

**Issue by jakobnissen** [avehtari/BDA_course_Aalto#4]
Dear Vehtari

1) The script `exercises/additional_files/psrf.py` is not compatible with Python3. This is because it uses the function `xrange`, which was removed in Python3. In order to make it Python3-compatible, you can simply have the following block in the top of the script:
```
try:
    xrange
except NameError:
    xrange = range
```
However, since the end-of-life Python2 is drawing near, [most cental Python projects have vowed to stop supporting Python 2 before 2020, including Numpy, PyStan, Scipy, Jupyter and Cython](https://python3statement.org/), and Python3 was released more than 10 years ago, I'd argue it instead might be worth just dropping Python 2 compatibility instead.

2) When given `return_extra=True`, the output `tau` is not documented.

**Comment by avehtari** [comment]
1. fixed this with your proposal. 

I'm aware of Python2 vs 3 and we have been supporting only Python3, but right now it was fastest to fix as you proposed. I'm happy to accept a pull request for complete fix.

2. I'll see to this

**Comment by MansMeg** [comment]
@avehtari What is the status here? Is it fixed now? Or should we let this pass since Python is deprecated?

**Comment by avehtari** [comment]
Python is still allowed, so we should help a little bit. Students should use ArviZ . It would be good to have an example how ArviZ is used.

**Comment by adhaka** [comment]
maybe, I can code up an example since I have been using ArviZ for a while now.

**Comment by tsivula** [comment]
Now updated `psrf.py`. Maybe a separate issue for ArviZ example should be put up.

**Comment by avehtari** [comment]
Closed by 9ff0c2
