### ISSUE TITLE
Re-write exercise 5 to include sub-questions under each question. (and update rubric accordingly)

### ISSUE THREAD

**Issue by kunalghosh** [avehtari/BDA_course_Aalto#45]
We should add sub-sections in each question particularly question 2. For example:

Refactor the following to
> 2. Include in the report the proposal distribution, number of chains used, the starting points (or the mechanism for generating them), the number of draws generated from each chain, and the warm-up length. Also plot the chains separately for alpha and beta, overlapping chains help to visually assess whether the chains have converged or not. However, in complex scenarios, visual assessment is not sufficient and Rˆ is a more robust indicator of convergence (of the metropolis chains).

2. The following questions pertain to the specifics of the metropolis algorithm:
  a. Was the proposal distribution used, mentioned in the report ?
  b. Were the number of metropolis chains mentioned ?
... etc.

This is much easier to refer back to in the rubric.

Task 2: Update the rubric to refer to these individual sub-questions.

**Comment by MansMeg** [comment]
Hasn't this been done now with the week-ends PR?

**Comment by MansMeg** [comment]
ping @kunalghosh

**Comment by kunalghosh** [comment]
@MansMeg Just took a look at [exercises/ex5.pdf](https://github.com/avehtari/BDA_course_Aalto/blob/master/exercises/ex5.pdf) hasn't been fixed yet. Will send a PR soon.

**Comment by kunalghosh** [comment]
Fixed as a part of 
https://github.com/avehtari/BDA_course_Aalto/pull/58/commits/c49e84defd2fac7dc305a36cb95616fcec10755e
