### ISSUE TITLE
Exercise 5, rubric consistency 

### ISSUE THREAD

**Issue by alexaushev** [avehtari/BDA_course_Aalto#50]
1. The rubric 5 does not have clear distinctions between the exercises, as a result some students decided to abandon the exercise-per-section structure of their reports.  -- see that the rest of the rubrics explicitly refer to the exercises in each question, the rubric 5 does not do this;
2. Some things in the rubric were not stated explicitly in the ex5.pdf -- the convergence discussion of the alpha and beta plots.
3. (Suggestion) I would make ex1 and ex2 more distinct. For example, it would be more intuitive if in the ex1 you only need to implement two functions, and in the ex2 you need to do the sampling reporting all relevant parameters (and the plots). Right now, the ex1 needs to do the implementation of two functions and the sampling, but you report the parameters of the sampling only in the ex2, which is not the most straightforward way of doing the experiments: first you do the experiment, and then you define the parameters.

**Comment by kunalghosh** [comment]
related to issue #45

**Comment by kunalghosh** [comment]
Fixed as a part of 
https://github.com/avehtari/BDA_course_Aalto/pull/58/commits/c49e84defd2fac7dc305a36cb95616fcec10755e
