### ISSUE TITLE
Include info on the 2nd round of submissions to gh-pages

### ISSUE THREAD

**Issue by TeemuSailynoja** [avehtari/BDA_course_Aalto#71]
Update the github.io course page to mention and give instructions on the possibility to submit all assignments at the end of the course for a second round of peergrading.

**Comment by TeemuSailynoja** [comment]
The chance to return all assignments in period III is mentioned in the FAQ. Is this enough or should it also be mentoioned on the assignments page?

**Comment by TeemuSailynoja** [comment]
@avehtari, Is it enough to mention the second chance to return assignments in the FAG, or should it be added to the Assignments page?

**Comment by avehtari** [comment]
It is mentioned in the assignments page.
