### ISSUE TITLE
Maybe an erratum?

### ISSUE THREAD

**Issue by winterwang** [avehtari/BDA_course_Aalto#74]
Hi, I might found a typo in the BDA3 book. Page 44 where there is derivation about the marginal distribution of Poisson data. The final line which shows the prior predictive distribution reduces to a negative binomial density. The one in the book is 

<img src="https://render.githubusercontent.com/render/math?math=p(y)%20%3D%20%7B%5Calpha%20%2By%20-1%7D%5Cchoose%20%7By%7D%5Cleft(%20%5Cfrac%7B%5Cbeta%7D%7B%5Cbeta%20%2B%201%7D%20%5Cright)%5E%5Calpha%20%5Cleft(%20%5Cfrac%7B1%7D%7B%5Cbeta%20%2B%201%7D%20%5Cright)%5Ey%0A">

Maybe the correct one is the following?

<img src="https://render.githubusercontent.com/render/math?math=p(y)%20%3D%20%7B%5Calpha%20%2By%20-1%7D%5Cchoose%20%7B%5Calpha%20-1%7D%5Cleft(%20%5Cfrac%7B%5Cbeta%7D%7B%5Cbeta%20%2B%201%7D%20%5Cright)%5E%5Calpha%20%5Cleft(%20%5Cfrac%7B1%7D%7B%5Cbeta%20%2B%201%7D%20%5Cright)%5Ey%0A">

**Comment by avehtari** [comment]
Negative binomial has several alternative formulas, see, e.g. https://en.wikipedia.org/wiki/Negative_binomial_distribution#Alternative_formulations

The one in book seems correct to me, but please elaborate your thinking why you assume it would be wrong?

**Comment by winterwang** [comment]
Thanks for the clarification. It was my mistake.
