### ISSUE TITLE
Add fictional examples of good help requests

### ISSUE THREAD

**Issue by avehtari** [avehtari/BDA_course_Aalto#77]
Add to assignments page examples:

Here are some fictional examples of good help requests:

*Chat: TODO: add BDA course specific example*

*Zoom: TODO: add BDA course specific example*

For comparison, see Parallel computing course examples http://ppc.cs.aalto.fi/2020/lab/

**Comment by topipa** [comment]
https://github.com/avehtari/BDA_course_Aalto/pull/79

**Comment by avehtari** [comment]
Thanks Topi!
