### ISSUE TITLE
outdated link in assignment 1

### ISSUE THREAD

**Issue by xyyuhans** [avehtari/BDA_course_Aalto#80]
>The  recommended  tool  in  this  course  is  R  (with  the  IDE  R-Studio).   You  candownload  Rhereand  R-Studiohere.   There  are  tons  of  tutorials,  videos  andintroductions to R and R-Studio online.  You can find some initial hints here.

Hi, the link (https://rstudio.com/online-learning/) in `You can find some initial hints here.` in assignment 1 is outdated.

**Comment by avehtari** [comment]
Thanks for reporting! Unfortunately I had forgot to check the issues as I've been following the course chat for the feedback, but it seems that you are the only one who has clicked that link. Fixed now.
