### ISSUE TITLE
Is it possible to get epub (or other scalable) version of the book?

### ISSUE THREAD

**Issue by ibobak** [avehtari/BDA_course_Aalto#82]
Dear Aki,

Thank you very much for this great course.

I just wanted to ask if it is possible to render the BDA book in PDF with 1.5 times bigger fonts, or to make epub/mobi/fb2 format?

I just want to make so that the book will display on Kindle DX (10 inch screen reader) with bigger fonts. 

Now the fonts are too small, reading on ebook is not comfortable.  It is possible only on computer monitor, which is also hard to read for long time (eyes pain).

Thanks in advance.

Regards,
Ihor

**Comment by avehtari** [comment]
Sorry, we are not able to do these at the moment. From the publishers page "Where the content of the eBook requires a specific layout, or contains maths or other special characters, the eBook will be available in PDF (PBK) format, which cannot be reflowed." https://www.routledge.com/Bayesian-Data-Analysis/Gelman-Carlin-Stern-Dunson-Vehtari-Rubin/p/book/9781439840955. At the moment, you might consider the printed book that has better readability.
