### ISSUE TITLE
Dead links on https://avehtari.github.io/BDA_course_Aalto/assignments_gsu.html

### ISSUE THREAD

**Issue by novica** [avehtari/BDA_course_Aalto#89]
Hi, 

I am trying to answer some of the questions on the registration form and thus browsing the webpage. I think the links to the schedule in this section 

```
Weekly assignments

There are 9 weekly assignments. Assignments are linked from the schedule and can also be found from git repo assignments folder. The deadline days for the assignments are given in the course schedule.
````

return 404. (link: `https://avehtari.github.io/BDA_course_Aalto/gsu.html#Schedule_2021`)

**Comment by avehtari** [comment]
Thanks, this has been fixed as it was reported also in the chat.
