### ISSUE TITLE
label error in demo10_2

### ISSUE THREAD

**Issue by asepsiswu** [avehtari/BDA_course_Aalto#96]
https://avehtari.github.io/BDA_R_demos/demos_ch10/demo10_2.html

comment line of `scale_color_discrete`  show red line is `g`  not `q`

> distr <- ggplot(data = df1) +
>   geom_line(aes(x, p, fill = grp, color = grp)) +
>   labs(title = 'Target and proposal distributions', x = '', y = '') +
>   scale_color_discrete(labels = c('q(theta|y)', 'g(theta)')) +
>   theme(legend.position = 'bottom', legend.title = element_blank())

**Comment by avehtari** [comment]
Thanks! Fixed.
