### ISSUE TITLE
Typo in slides

### ISSUE THREAD

**Issue by matthewgilbert** [avehtari/BDA_course_Aalto#97]
I believe there is a typo on page 10 of [Chapter 5 slides](https://github.com/avehtari/BDA_course_Aalto/blob/master/slides/slides_ch5.pdf),

![error](https://user-images.githubusercontent.com/2401026/126389862-2f84fb57-37ac-4b48-befb-4532579aa7d2.png)

**Comment by avehtari** [comment]
Thanks! Fixed.
